# Generated by Django 3.2.8 on 2021-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='blogs/', verbose_name='Фотография'),
        ),
    ]
