# Generated by Django 3.2.8 on 2021-11-11 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20211104_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Содержимое'),
        ),
    ]
