# Generated by Django 3.2.8 on 2021-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сниппет'),
        ),
    ]
