# Generated by Django 3.2.8 on 2021-11-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
